name: weather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  #Service Locator
  get_it: ^7.6.4
  rxdart: ^0.27.7
  http: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

